### PR TITLE
Enemy Triple shot update

### PR DESCRIPTION
**Pull request by StevenMccracken**
Utilizes object pooling

### CODE REVIEW

**Comment by Darkchicken** [comment]
Hmm, still something not letting me merge this branch. Everything looks like its ok though. I may just copy the code into a new script on my end

**Comment by StevenMccracken** [comment]
Should I submit a new pull request?

**Comment by Darkchicken** [comment]
Dont worry about it, I can just copy your code into a new script on my end since we dont know why its being weird

**Comment by ARGutierrez** [comment]
In the future we should always try to figure out why commits are broken. Copy pasting code does circumvent the issue temporarily, but if this keeps happening with future commits, then there may be more deep-rooted issues.

Pop into the command line next time and run a "git status" to see if there are any merge conflicts.

**Comment by Darkchicken** [comment]
Good point. Besides, the copy-pasting of the code didnt work anyway, there are issues with the code itself. I closed the pull request because the code will need to be overhauled and a new pull request made

**Pull request closed without merging**
