### PR TITLE
test1

### PR DESCRIPTION
**Pull request by Fierfek**

### CODE REVIEW

**Comment by ARGutierrez** [comment]
What changed here? I only see a bunch of files in the Library folder (which shouldn't be committed anyway).

**Comment by Fierfek** [comment]
I'm writing instructions on how to use github. Needed to create a new branch and a pull request to double check my work.

**Comment by Fierfek** [comment]
I'm not sue what's up with the library stuff.

**Comment by ARGutierrez** [comment]
Well, apparently since it had already been committed to the repo, the only way for the gitignore to actually ignore it is to make sure its deleted. So I went ahead and did that and pushed the commit,

**Pull request closed without merging**
